config/routes.rb
Rails.application.routes.draw do

  root :to => "homes#top"

  get 'homes/top'

  resources :books
  
  patch 'books/:id' => 'books#update', as: 'update_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all

  end

  def create
    flash[:notice] = "Book was successfully created."
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    flash[:notice] = "Book was successfully update."
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'

  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>



<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h3>Title</h3>
<%= f.text_field :title %>

<h3>Body</h3>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<%= link_to "Show", "/books/#{@book.id}" %> | <%= link_to "Back", "/books" %>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>

<% end %>

<% @books.each do |book| %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", "/books/#{book.id}" %></td>
      <td><%= link_to "Edit", "/books/#{book.id}/edit" %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
  </tbody>
</table>

<% end %>

<h2>New Book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url:'/books', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
  
<% end %>

<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>

<%= link_to "Edit", "/books/#{@book.id}/edit" %> | <%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>
<!--
<p>Find me in app/views/homes/top.html.erb</p>
-->
<P><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</P>
<p>印象を共有し交換することができます</p>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>